site_name: Apunts UD02 — Introducció a Java (DAM)
site_description: Apunts de la UD02 per a Programació 1r DAM

docs_dir: docs
site_dir: siteV2

theme:
  name: material
  language: ca
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Canvia a mode oscur
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Canvia a mode clar

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - def_list

plugins:
  - search
  - glightbox
 
 

extra_css:
  - css/styles.css   # <- coincide con tu árbol

nav:
  - "Inici": "index.md"
  - "UD02":
    - "UD02 - Introducció a Java (DAM)": "ud02/01-introduccio-a-java.md"
    - "1. Agenda": "ud02/02-agenda.md"
    - "2. Introducció a Java": "ud02/03-introduccio.md"
    - "3. Instal·lació del JDK": "ud02/04-installacio-del-jdk.md"
    - "4. Instal·lació de Visual Studio Code": "ud02/05-installacio-de-visual-studio-code.md"
    - "5. El primer programa: “Hola Món”": "ud02/06-el-primer-programa-hola-mon.md"
    - "6. Variables i tipus": "ud02/07-variables-i-tipus.md"
    - "7. Comprovació de condicions": "ud02/08-comprovacio-de-condicions.md"
    - "8. Bucles": "ud02/09-bucles.md"
    - "9. Tipus de bucles en Java": "ud02/10-tipus-de-bucles-en-java.md"
    - "10. Control del flux dins dels bucles": "ud02/11-control-del-flux-dins-dels-bucles.md"
    - "11. Arrays i cadenes": "ud02/12-arrays-i-cadenes.md"
    - "12. Dades introduïdes per l’usuari": "ud02/13-dadesUsuari.md"

